### ISSUE TITLE
npm ERR! Error: failed to fetch from registry: es6-promise

### ISSUE THREAD

**Issue by yunlongw** [actions/npm#13]
```
npm ERR! Error: failed to fetch from registry: es6-promise
npm ERR!     at /usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:32:9)
npm ERR!     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:137:18)
npm ERR!     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:109:22)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:198:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/main.js:356:14)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1254:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! 
npm ERR! System Linux 3.10.0-862.el7.x86_64
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /home/wwwroot/vue-paper-dashboard
npm ERR! node -v v0.6.9
npm ERR! npm -v 1.1.0-3
npm ERR! message failed to fetch from registry: es6-promise
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/wwwroot/vue-paper-dashboard/npm-debug.log
npm not ok
```

**Comment by mcolyer** [comment]
@yunlongw is this still happening? If it is, does `npm install` work in other environments and would you be willing to post your `package.json` file?

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
