### ISSUE TITLE
missing python executable

### ISSUE THREAD

**Issue by piot** [actions/npm#21]
```
### STARTED Build 21:20:59Z

Pulling image: gcr.io/github-actions-images/action-runner:latest
latest: Pulling from github-actions-images/action-runner
cd784148e348: Already exists
ee54f991f2ab: Pulling fs layer
87095b8869b4: Pulling fs layer
07b55d466225: Pulling fs layer
a3aecf06b8e1: Pulling fs layer
a3aecf06b8e1: Waiting
ee54f991f2ab: Verifying Checksum
ee54f991f2ab: Download complete
87095b8869b4: Verifying Checksum
87095b8869b4: Download complete
07b55d466225: Verifying Checksum
07b55d466225: Download complete
a3aecf06b8e1: Verifying Checksum
a3aecf06b8e1: Download complete
ee54f991f2ab: Pull complete
87095b8869b4: Pull complete
07b55d466225: Pull complete
a3aecf06b8e1: Pull complete
Digest: sha256:888acf663d6bb9cae858ddc479a6b41a2db0317d8f7abaf7f54bca5a74884ba2
Status: Downloaded newer image for gcr.io/github-actions-images/action-runner:latest
Step 1/13 : FROM node:10-slim
10-slim: Pulling from library/node
5e6ec7f28fb7: Already exists
fe40c2f302db: Pulling fs layer
dec5ad5a153b: Pulling fs layer
f285a29b16ca: Pulling fs layer
fe40c2f302db: Verifying Checksum
fe40c2f302db: Download complete
f285a29b16ca: Verifying Checksum
f285a29b16ca: Download complete
fe40c2f302db: Pull complete
dec5ad5a153b: Verifying Checksum
dec5ad5a153b: Download complete
dec5ad5a153b: Pull complete
f285a29b16ca: Pull complete
Digest: sha256:24b828a44f6c8a6e28d7c9bcdc2cc2d245fab6cfc941627ee1eb0336d2232881
Status: Downloaded newer image for node:10-slim
 ---> 1ee14be408b9
Step 2/13 : LABEL version="1.0.0"
 ---> Running in d7159a9ba355
 ---> 292912395eb7
Step 3/13 : LABEL repository="http://github.com/actions/npm"
 ---> Running in ae7e81f3081b
 ---> 65b8f06164aa
Step 4/13 : LABEL homepage="http://github.com/actions/npm"
 ---> Running in 57eb9f16a3e3
 ---> 5d8e5e8e6edc
Step 5/13 : LABEL maintainer="GitHub Actions <support+actions@github.com>"
 ---> Running in 83422d9a5725
 ---> a494e1f3efa4
Step 6/13 : LABEL com.github.actions.name="GitHub Action for npm"
 ---> Running in 98b5955917a3
 ---> e5602babe370
Step 7/13 : LABEL com.github.actions.description="Wraps the npm CLI to enable common npm commands."
 ---> Running in d924e6a34675
 ---> 417f16685546
Step 8/13 : LABEL com.github.actions.icon="package"
 ---> Running in e0934904517f
 ---> 7f10e8ac33d1
Step 9/13 : LABEL com.github.actions.color="red"
 ---> Running in 848a0c8e3fcf
 ---> c48169837219
Step 10/13 : COPY LICENSE README.md THIRD_PARTY_NOTICE.md /
 ---> e9b08f64f3e8
Step 11/13 : COPY "entrypoint.sh" "/entrypoint.sh"
 ---> ac45653b02d7
Step 12/13 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Running in 7f4c1ca2cca6
 ---> 21d0ffe27296
Step 13/13 : CMD ["help"]
 ---> Running in c84161899bd6
 ---> 37e3f33f3a9a
Successfully built 37e3f33f3a9a
Successfully tagged gcr.io/gct-12-vq6qou0yy6q965pvnfe3zs6/484654f7adf6911ca799c01d40b80af4456b46c3418f33934c643ccc7f245f38/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest

> node-expat@2.3.17 install /github/workspace/node_modules/node-expat
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Linux 4.15.0-1026-gcp
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /github/workspace/node_modules/node-expat
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN pack-dependency@1.0.0 No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.17 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2019-01-24T21_21_27_174Z-debug.log

### FAILED Build 21:21:35Z (36.724s)
```

**Comment by mcolyer** [comment]
@piot so our NPM action doesn't include python. Uf you'd like to create an action that includes both I'd suggest you create a Dockerfile that references this one and then adds the required python packages. Alternatively, if you already have a docker container that contains everything that you want you can use that as well.
